### ISSUE TITLE
Priority Queue（優先順付きキュー）

### ISSUE THREAD

**Issue by athenaeum-school** [athenaeum-school/Cocos2dxBook#2]
キューの並び替えをしたものがPriority Queueです。
QueueよりPriorityQueueの方がより多く使われる機会があると思います。
面接問題集のほうのトピックとしては最適かと推量します。

・Selection Sort（遅くなりがち）
・Insertion Sort（遅くなりがち）
・Heap Sort（これがおすすめ）
・Merge Sort
・Quick Sort

Heapデータ構造とHeapソートアルゴリズムの詳細については（必要であれば）説明します。
上２つのソートについては、知らなくとも実装してしまっていたとしても
驚かない単純なアルゴリズムです。

時間があれば、これも実装してみると良いかもしれません。

**Comment by Nadd3564** [comment]
わかりました。

**Comment by athenaeum-school** [comment]
ヒープの簡単な例です。

![array](https://cloud.githubusercontent.com/assets/8011089/5920626/4d922920-a681-11e4-94eb-73cbe4c4257f.gif)
- 各要素をノードとよぶ（言葉に意味はないので、深く考えないでください）
- root（木の根）ノードはarray[1]に常にある
- 左の子ノードは、array[2] 
- 右の子ノードは、array[3]
- ノードがarray[k]の場合、その左の子はarray[k_2]、当該ノードの右の子はarray[k_2 + 1]
- 親ノードは[k/2]にある。割れない場合は四捨五入。

ソース：
http://pages.cs.wisc.edu/~vernon/cs367/notes/11.PRIORITY-Q.html

![insert](https://cloud.githubusercontent.com/assets/8011089/5920534/a8c63a3a-a680-11e4-92ec-d1a43f14f228.gif)

練習：
１０、６０、２０、４、８を上記の二分木に挿入してみたください（３４挿入の後）
