### ISSUE TITLE
各Patternについて

### ISSUE THREAD

**Issue by Nadd3564** [athenaeum-school/Cocos2dxBook#5]
Before 適用前
Apply 適用後

元はBefore状態になっており、比較のために差分化しています。

**Comment by Nadd3564** [comment]
お疲れ様です。
各デザインのステータスをお伝えします。
・Queue 着手可能
・SandBox 着手可能
・Component 着手可能
・TypeObject 着手不可

という状況です。
よろしくお願いします。

**Comment by athenaeum-school** [comment]
NGの意味が何を指すかは分かりませんが、
実装手法としてはSkypeで示した（SampleObject）ものに加え、
AudioComponentは（実装のない）抽象クラスとし、実装クラスをConcreteAudioComponentとしてAudioComponentを継承するクラスを追加します。

またAudioComponentの参照（ポインター）を持つクラス（SampleObject）は、
AudioComponentと１対１でなく、1対複数（aggregation）の
関係を持つとする場合は、`vector<AudioComponent*>`といったように参照を持つ必要があります。1対複数の縛りはCompositeデザインパターンの規約を満たす場合は必要となります。

SampleObjectのコンストラクターで、ConcreteAudioComponentのインスタンスを生成して、AudioComponentとして保管すれば終了です。

**Comment by Nadd3564** [comment]
承知しました。
紛らわしくて申し訳ございません。
まだ執筆が出来る状況ではないという事をお伝えしたつもりでした。

**Comment by athenaeum-school** [comment]
「執筆」の正確な意味についても分からないのですが、それについてはSkypeで明日説明をお願いします。

コードについては、分かりやすいように上記の内容をクラス図で当てはめておきます。

Component：  AudioComponent
葉：ConcreteAudioComponent
Composite： SampleObject　（ここで、AudioComponentのポインタを持ち、ConcreteAudioComponentのインスタンスをコンストラクターで生成して、AudioComponentに代入）

といった様態となるかと思いますので、修正して頂けると助かります。

**Comment by Nadd3564** [comment]
わかりました。
ご丁寧にありがとうございます。

**Comment by athenaeum-school** [comment]
一点誤解が生じそうなので補足です。

CompositeとComponentが１対複数の関係を持つとする場合で、Componentが類似の共通インターフェースを持つ場合はCompositeが共通インターフェースを実装して、`vector<Component*>`等の参照を持つといった設計もあるでしょうが、

```
private:
 CameraComponent * cc;
 AudioComponent* ac;
```

といった関連性の薄いコンポーネントを持つ場合、vector<Component*>では対応できないため、CompositeがComponentの派生クラスとはならなくてもいいはずです。

趣旨があっていればクラス図に厳密に従う必要はないと考えますので、柔軟に考えてください。

**Comment by Nadd3564** [comment]
Queueで不具合を確認したため、修正しました。
大変お手数ですが、反映をよろしくお願いします。

**Comment by Nadd3564** [comment]
全パターン適応完了。
